# Generated by Django 5.2.3 on 2026-08-02 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('parchi_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Parchi KG')),
                ('mixing_actual_compound', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mixing Actual Compound')),
                ('wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wastage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TyreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre', models.CharField(max_length=50, verbose_name='TYRE')),
                ('pattern', models.CharField(max_length=80, verbose_name='PATTERN')),
                ('type', models.CharField(max_length=20, verbose_name='TYPE')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Standard Weight (KG per tyre)')),
                ('repair_tyre_stock', models.IntegerField(default=0, verbose_name='Repair Tyre Stock')),
                ('rfm_ok_tyre', models.IntegerField(default=0, verbose_name='RFM OK Tyre')),
                ('old_tyres_2025', models.IntegerField(default=0, verbose_name='2025 Old Tyres')),
                ('stock', models.IntegerField(default=0, verbose_name='STOCK')),
                ('on_hold_export', models.IntegerField(default=0, verbose_name='On hold for Export / OR')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tyre', 'pattern', 'type'],
                'unique_together': {('tyre', 'pattern', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('production', 'Production (Daily Curing)'), ('dispatch', 'Dispatch'), ('adjustment', 'Stock Adjustment')], max_length=15)),
                ('bucket', models.CharField(choices=[('stock', 'STOCK'), ('repair_tyre_stock', 'Repair Tyre Stock'), ('rfm_ok_tyre', 'RFM OK Tyre'), ('old_tyres_2025', '2025 Old Tyres'), ('on_hold_export', 'On hold for Export / OR')], default='stock', max_length=25)),
                ('quantity', models.IntegerField(help_text='Enter positive quantity')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Actual Weight (KG)')),
                ('all_curing', models.IntegerField(default=0, verbose_name='All Curing')),
                ('production_tyre', models.IntegerField(default=0, verbose_name='Production Tyre')),
                ('repair', models.IntegerField(default=0, verbose_name='Repair')),
                ('second_grade', models.IntegerField(default=0, verbose_name='2nd Grade')),
                ('third_grade', models.IntegerField(default=0, verbose_name='3rd Grade')),
                ('lose_tyre', models.IntegerField(default=0, verbose_name='Lose Tyre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('tyre_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stock.tyreitem')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
