# Generated by Django 5.2.3 on 2026-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreitem',
            name='second_stock',
            field=models.IntegerField(default=0, verbose_name='2nd Grade Stock'),
        ),
        migrations.AddField(
            model_name='tyreitem',
            name='third_stock',
            field=models.IntegerField(default=0, verbose_name='3rd Grade Stock'),
        ),
    ]
