# Generated by Django 5.2.3 on 2026-08-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('voucher_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('party_gstin', models.CharField(blank=True, max_length=20)),
                ('party_address', models.TextField(blank=True)),
                ('consignee_name', models.CharField(blank=True, max_length=200)),
                ('consignee_gstin', models.CharField(blank=True, max_length=20)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('gst_registration_type', models.CharField(blank=True, max_length=50)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_synced', models.BooleanField(default=False, help_text='True if all line items matched & stock was reduced')),
                ('raw_payload', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-voucher_date', '-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='TallyItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_item_name', models.CharField(max_length=150, unique=True)),
                ('module', models.CharField(choices=[('tyre', 'Auto Tyre'), ('tube', 'Cycle Tube'), ('cycletyre', 'Cycle Tyre')], max_length=15)),
                ('item_id', models.PositiveIntegerField(help_text='The ID of the matching item in that module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tally_item_name'],
            },
        ),
        migrations.CreateModel(
            name='TallyPendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_item_name', models.CharField(max_length=150)),
                ('qty', models.IntegerField()),
                ('voucher_number', models.CharField(max_length=50)),
                ('voucher_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(choices=[('unmapped', 'Item Not Mapped'), ('insufficient_stock', 'Insufficient Stock')], max_length=25)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='tallysync.tallyinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TallySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tallysync.tallyinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
