# Generated by Django 5.2.3 on 2026-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallypendingitem',
            name='category_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
