# Generated by Django 5.2.3 on 2026-08-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0002_tallypendingitem_category_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('voucher_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='voucher_type',
            field=models.CharField(blank=True, default='Sales', max_length=30),
        ),
        migrations.CreateModel(
            name='TallyInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_item_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mapped_module', models.CharField(blank=True, max_length=15)),
                ('mapped_item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tallysync.tallyinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
