# Generated by Django 5.2.3 on 2026-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Google AI Studio Gemini API Key (e.g. AIzaSy...). Rotate/update anytime here.', max_length=255, verbose_name='Gemini API Key')),
                ('model_name', models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (Recommended — Fastest & Smartest)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Fast & High Volume)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Stable & Highly Compatible)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Deep Reasoning & Large Analysis)')], default='gemini-2.5-flash', help_text='Primary model used by the AI Agent.', max_length=50, verbose_name='Active AI Model')),
                ('fallback_model', models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (Recommended — Fastest & Smartest)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Fast & High Volume)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Stable & Highly Compatible)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Deep Reasoning & Large Analysis)')], default='gemini-1.5-flash', help_text='Secondary model used automatically if the primary model hits quota/rate limits.', max_length=50, verbose_name='Fallback Model')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable the AI Agent assistant across the ERP.', verbose_name='Enable AI Assistant')),
                ('temperature', models.FloatField(default=0.4, help_text='0.0 to 1.0. Lower values (0.2-0.4) are more precise for ERP data; higher is more conversational.', verbose_name='Temperature (Creativity)')),
                ('system_instructions_extra', models.TextField(blank=True, help_text='Optional custom instructions to add to the ERP system prompt (e.g. custom pricing policies, holiday notices).', verbose_name='Extra Prompt Instructions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration & API Keys',
                'verbose_name_plural': 'AI Configuration & API Keys',
            },
        ),
    ]
