# Generated by Django 5.2.3 on 2026-08-06 16:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTyreDailyManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('parchi_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Packing Parch Kg')),
                ('mixing_actual_compound', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mixing Actual Compound')),
                ('chakka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chakka')),
                ('calander_bias_cutt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calander Bias Cutt.')),
                ('packing_wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Packing Wastage')),
                ('tar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Tyre Daily Manual Entry',
                'verbose_name_plural': 'Cycle Tyre Daily Manual Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CycleTyreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(max_length=30, verbose_name='BOX TYPE')),
                ('size', models.CharField(max_length=50, verbose_name='SIZE')),
                ('material', models.CharField(max_length=20, verbose_name='MATERIAL')),
                ('brand', models.CharField(max_length=80, verbose_name='BRAND')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, verbose_name='Weight (Kg)')),
                ('stock', models.IntegerField(default=0, verbose_name='STOCK (1st Grade / Black)')),
                ('second_stock', models.IntegerField(default=0, verbose_name='2nd Grade Stock')),
                ('rfm_stock', models.IntegerField(default=0, verbose_name='R.F.M. Stock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['size', 'box_type', 'material', 'brand'],
                'unique_together': {('box_type', 'size', 'material', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='CycleTyreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('production', 'Production'), ('sale', 'Sale / Dispatch'), ('adjustment', 'Stock Adjustment')], max_length=15)),
                ('bucket', models.CharField(choices=[('stock', 'STOCK (1st Grade)'), ('second_stock', '2nd Grade Stock'), ('rfm_stock', 'R.F.M. Stock')], default='stock', max_length=15)),
                ('quantity', models.IntegerField()),
                ('all_curing', models.IntegerField(default=0, verbose_name='All Curing')),
                ('first_grade', models.IntegerField(default=0, verbose_name='1st Grade (Black)')),
                ('second_grade', models.IntegerField(default=0, verbose_name='2nd Grade')),
                ('rejected_grade', models.IntegerField(default=0, verbose_name='Rejected Grade')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycletyre_entries', to=settings.AUTH_USER_MODEL)),
                ('tyre_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cycletyres.cycletyreitem')),
            ],
            options={
                'verbose_name_plural': 'Cycle tyre entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
