# Generated by Django 5.2.3 on 2026-08-06 15:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTubeDailyManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('valve_body_issued', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valve Body Issued')),
                ('actual_wt_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual wt kgs (Gross)')),
                ('actual_mixing_compound', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Mixing Compound')),
                ('jali', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jali (Wastage)')),
                ('die_wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Die Wastage')),
                ('tube_cutting', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tube Cutting')),
                ('total_tube_waste', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Tube Waste')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Tube Daily Manual Entry',
                'verbose_name_plural': 'Cycle Tube Daily Manual Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CycleTubeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='SIZE')),
                ('type', models.CharField(max_length=20, verbose_name='TYPE')),
                ('brand', models.CharField(max_length=80, verbose_name='BRAND')),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, verbose_name='Weight (Kg)')),
                ('stock', models.IntegerField(default=0, verbose_name='STOCK')),
                ('rfm_stock', models.IntegerField(default=0, verbose_name='R.F.M. Stock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['size', 'type', 'brand'],
                'unique_together': {('size', 'type', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='CycleTubeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('production', 'Production'), ('sale', 'Sale / Dispatch'), ('adjustment', 'Stock Adjustment')], max_length=15)),
                ('bucket', models.CharField(choices=[('stock', 'STOCK'), ('rfm_stock', 'R.F.M. Stock')], default='stock', max_length=15)),
                ('quantity', models.IntegerField()),
                ('tube_quality', models.CharField(choices=[('normal', 'Normal'), ('molded', 'Molded'), ('second', 'Second')], default='normal', max_length=10, verbose_name='Tube Quality')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycletube_entries', to=settings.AUTH_USER_MODEL)),
                ('tube_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cycletube.cycletubeitem')),
            ],
            options={
                'verbose_name_plural': 'Cycle tube entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
