# Generated by Django 5.2.3 on 2026-08-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycletube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycletubedailymanualentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='cycletubeentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='actual_mixing_compound',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='actual_wt_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='die_wastage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='jali',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='total_tube_waste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='tube_cutting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubedailymanualentry',
            name='valve_body_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycletubeentry',
            name='tube_quality',
            field=models.CharField(choices=[('normal', 'Normal'), ('molded', 'Molded'), ('second', 'Second')], default='normal', max_length=10),
        ),
    ]
